# Generated by Django 3.2.9 on 2021-11-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_alter_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
