# Generated by Django 3.2.9 on 2021-11-22 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0013_remove_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom.order')),
            ],
        ),
        migrations.DeleteModel(
            name='DeliveryAddress',
        ),
    ]
