# Generated by Django 3.2.9 on 2021-11-23 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0018_rename_user_shipping_address_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryAddress',
        ),
    ]
