# Generated by Django 3.2.9 on 2021-11-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0023_order_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='product',
        ),
    ]
