# Generated by Django 3.2.9 on 2021-11-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0027_cartitem_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_cost',
            field=models.IntegerField(default=0),
        ),
    ]
